### PR TITLE
Moved repository to actions

### PR DESCRIPTION
**Pull request by evaherrada**

### CODE REVIEW

**Review by ladyada — APPROVED** [review]

**Comment by ladyada** [comment]
can merge once passes

**Review by ladyada — CHANGES_REQUESTED** [review]
hi ya gotta spell it right - see
https://www.arduinolibraries.info/libraries/adafruit-unified-sensor
for the name

**Comment by evaherrada** [comment]
@ladyada Yeah, I think spelling it right might help lol. I guess I put Arduino instead of Adafruit

**Review by ladyada — APPROVED** [review]
nice!

**Pull request merged**
